// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32s3_4.3b_lgvl

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_LblButton1 = NULL;
lv_obj_t * ui_LblButton2 = NULL;
lv_obj_t * ui_LblScreen = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        func_countUp(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        func_countDown(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc1, 150);
    lv_obj_set_height(ui_Arc1, 150);
    lv_obj_set_x(ui_Arc1, -28);
    lv_obj_set_y(ui_Arc1, -101);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 225);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -192);
    lv_obj_set_y(ui_Button1, 91);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 219);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 120);
    lv_obj_set_y(ui_Button2, 87);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LblButton1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LblButton1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblButton1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblButton1, -192);
    lv_obj_set_y(ui_LblButton1, 89);
    lv_obj_set_align(ui_LblButton1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblButton1, "BUTTON 1");
    lv_obj_set_style_text_color(ui_LblButton1, lv_color_hex(0x07082D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblButton1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblButton2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LblButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblButton2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblButton2, 118);
    lv_obj_set_y(ui_LblButton2, 87);
    lv_obj_set_align(ui_LblButton2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblButton2, "BUTTON 2");
    lv_obj_set_style_text_color(ui_LblButton2, lv_color_hex(0x07082D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblButton2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblScreen = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LblScreen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblScreen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LblScreen, 6);
    lv_obj_set_y(ui_LblScreen, 0);
    lv_obj_set_align(ui_LblScreen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblScreen, "Hello my First lgvl");
    lv_obj_set_style_text_color(ui_LblScreen, lv_color_hex(0x24FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblScreen, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Arc1 = NULL;
    ui_Button1 = NULL;
    ui_Button2 = NULL;
    ui_LblButton1 = NULL;
    ui_LblButton2 = NULL;
    ui_LblScreen = NULL;

}
