// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32s3_4.3b_lgvl

#include "ui.h"

void func_countUp(lv_event_t * e)
{
	// Your code here
}

void func_countDown(lv_event_t * e)
{
	// Your code here
}
