// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: esp32s3_4.3b_lgvl

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void func_countUp(lv_event_t * e);
void func_countDown(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
